[tool.black]
line-length = 99
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | build
  | conf
  | contrib
  | data
  | docs
  | media
  | node_modules
  | shared-ci-files
  | static
  | tools
)/
  | .*/migrations/.*.py
'''

[tool.isort]
line_length = 99
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
force_single_line = true
profile = "black"
skip = [
   ]

known_future_library = ['future', '__future__']

[tool.mypy]

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true


[tool.coverage.report]
exclude_lines = [
    "pass",
    "pragma: no cover",
    "raise NotImplemented",
    "\\.\\.\\.",
]
omit = [
   "src/*/tests/*",
   "src/**/migrations/*"
]